### ISSUE TITLE
Calling UI stuff updating function from not main thread

### ISSUE THREAD

**Issue by MarkoN-Hexele** [bgreenlee/WeatherBar#1]
Original function: Updating UI stuff from async network routine ...
func update(weather: Weather) {
        cityTextField.stringValue = weather.city
        currentConditionsTextField.stringValue = "\(Int(weather.currentTemp))°F and \(weather.conditions)"
        imageView.image = NSImage(named: weather.icon)
    }

Proposed change:
func update(weather: Weather) {
        dispatch_async(dispatch_get_main_queue()) {
            cityTextField.stringValue = weather.city
            currentConditionsTextField.stringValue = "\(Int(weather.currentTemp))°F and \(weather.conditions)"
            imageView.image = NSImage(named: weather.icon)
        }
    }

**Comment by bgreenlee** [comment]
Thank you! Sorry it took so long, but I just got around to updating it for Swift 2
