### ISSUE TITLE
Nothing shows in status bar

### ISSUE THREAD

**Issue by tejasmanohar** [bgreenlee/WeatherBar#11]
I have the following code in AppDelegate.swift and was wondering if you have any ideas why nothing may be showing up in the status bar. I'm on High Sierra w/ XCode 9. Had to change a couple things in the code, as they wouldn't compile as is (e.g. NSStatusItem.variableLength).

```swift
import Cocoa

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {

    @IBOutlet weak var statusMenu: NSMenu!
    
    let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    
    @IBAction func quitClicked(_ sender: NSMenuItem) {
        NSApplication.shared.terminate(self)
    }
    
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        let icon = NSImage(named: NSImage.Name("statusIcon"))
        icon?.isTemplate = true // best for dark mode
        statusItem.image = icon
        statusItem.menu = statusMenu
    }
    
    func applicationWillTerminate(aNotification: NSNotification) {
        // Insert code here to tear down your application
    }


}
```

**Comment by raysarebest** [comment]
This is definitely a problem with the tutorial. In the initial part of the tutorial, it instructs you to use the symbol:

```swift
func applicationDidFinishLaunching(aNotification: NSNotification) {
```

However, the correct symbol from the `NSApplicationDelegate` is:

```swift
func applicationDidFinishLaunching(_ aNotification: Notification) {
```

Notice the underscore for the argument label in the 2nd example, which is the difference between the method signature being `applicationDidFinishLaunching(aNotification:)` and `applicationDidFinishLaunching(_:)`. This is probably an artifact of running the Swift Migration Tool on a previous version of Swift, but nonetheless, the tutorial is incorrect and should be changed

**Comment by bgreenlee** [comment]
Let me know if this fixes your issue (I haven't had a chance to run through it again myself)

**Comment by tejasmanohar** [comment]
It did!
