### ISSUE TITLE
convert to new Swift syntax 

### ISSUE THREAD

**Issue by gernotstarke** [bgreenlee/WeatherBar#2]
when opening project in Swift 7, conversion to new syntax yields
some errors (some "as!" conversion required, some error handling
currently missing).

(thx btw for the tutorial, very useful work!)

**Comment by bgreenlee** [comment]
Yes, I know. It's on my TODO list to update it for Xcode 7/Swift 2. Soon!

**Comment by bgreenlee** [comment]
Ok, it's been updated for Swift 2. Let me know if you have any issues/corrections!
