### ISSUE TITLE
Some code is missing in the tutorial.

### ISSUE THREAD

**Issue by freeism** [bgreenlee/WeatherBar#4]
Hi, this is Kang.

I am beginner of mac os development.
I was confused, because of missing some code in the tutorial (http://footle.org/WeatherBar)
I wanna let you know that, and I hope never be any other beginners confused.

The definition of fetchWeather function needs success params at Callback Implementation Part.
ex. func fetchWeather(query: String, success: (Weather) -> Void) {

Thank you for your tutorial. It is very helpful for me.

Best Regards,
Kang.

**Comment by bgreenlee** [comment]
Sorry for taking so long to get back to you on this. I've pushed a fix. Thank you so much for reporting this!
