### ISSUE TITLE
Errors (w/screenshot)

### ISSUE THREAD

**Issue by echezbro** [bgreenlee/WeatherBar#5]
Thanks for the project! New to Swift and looking to run this in Xcode. Any idea why pulling the repo and running the simulator causes these errors? Thanks!

<img width="390" alt="screen shot 2015-12-28 at 9 26 49 pm" src="https://cloud.githubusercontent.com/assets/844130/12029863/c8d0aa78-ada9-11e5-96c0-15c0080e90f7.png">

**Comment by bgreenlee** [comment]
Which version of Xcode are you running?






On Mon, Dec 28, 2015 at 9:27 PM -0800, "echezbro" <notifications@github.com> wrote:












Thanks for the project! New to Swift and looking to run this in Xcode. Any idea why pulling the repo and running the simulator causes these errors? Thanks!

**Comment by echezbro** [comment]
6.4

On Mon, Dec 28, 2015 at 11:37 PM, Brad Greenlee <notifications@github.com>
wrote:

> Which version of Xcode are you running?
>
>
>
>
>
>
> On Mon, Dec 28, 2015 at 9:27 PM -0800, "echezbro" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
>
>
> Thanks for the project! New to Swift and looking to run this in Xcode. Any
> idea why pulling the repo and running the simulator causes these errors?
> Thanks!
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bgreenlee/WeatherBar/issues/5#issuecomment-167722403>.
>



-- 
Eric Chesbrough
248.632.2108
ericchesbrough.com
